services:
  - type: web
    name: tds-solver
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --bind 0.0.0.0:$PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: AIPROXY_TOKEN
        sync: false
      - key: SESSION_SECRET
        generateValue: true